### ISSUE TITLE
Highlight Spaces, "Personal" and "Shares" area

### ISSUE THREAD

**Issue by PhMemmel** [owncloud/moodle-repository_ocis#53]
To distinguish between normal directories and Spaces as well as the areas "Personal" and "Shares" there should be an option to highlight these ones in contrast to the normal directories, like the ocis desktop client does it.

Suggestion:
- Add a config setting in the repository instance settings for a URL to a specific icon.
- If config option is being left empty the mentioned special directories will just appear as usual directories.
- If a valid URL to an icon is being configured these folders will show this icon instead of the default directory icon
- If the URL config string does not start with "http", it should be considered as relative to the moodle webroot

**Comment by individual-it** [comment]
should be fixed by #54

an additional approach could be to use the images that can be set in ocis itself
![grafik](https://github.com/owncloud/moodle-repository_ocis/assets/2425577/992f8319-505c-4006-bcbc-6e854c0be567)

If that is needed/wanted please open a new issue. It would be a bit more work because those images need to be pulled from ocis and the SDK does not support that yet.
