### ISSUE TITLE
Bug: Stuck in session when server not available

### ISSUE THREAD

**Issue by PhMemmel** [owncloud/moodle-repository_ocis#80]
To reproduce:
- Start filepicker
- Select ocis repository
- Successfully authenticate over a global IDP with a user that does not have access to the target ocis instance
- Error "Could not connect to ownCloud Infinite Scale server" appears which is fine
- The user however now is stuck in this state. There is no way to logout again and log into the repository with another account.
- Additionally the error message will appear whenever the user starts the file picker, no matter if he tries to access the ocis repo or not

This state will also persist after logging out and logging in again from moodle, clearing browser cache etc., because the offline_access token already seems to be there.

Request:
- There has to be a possibility in these cases to clear the authentication and re-authenticate.

**Comment by individual-it** [comment]
A similar issue happens when  user is deleted in ocis after a token was given to moodle

**Comment by individual-it** [comment]
The main problem should be fixed by #83, but there is one thing to discuss as there are other cases where similar things can happen but the user would be able to recover himself.

E.g. 
1. user logs in correctly to ocis
2. user browses spaces and folders
3. user gets disabled in ocis
4. on the next click in the file-picker (e.g. selecting a subfolder) the user would see `Authorization to ownCloud Infinite Scale server failed. Please try to logout of the repository and login again`
5. BUT now the user still has the `logout` button to try to logout and login again.

@PhMemmel for cases where the user could theoretically recover, should we still do an auto-logout and delete the token?

**Comment by PhMemmel** [comment]
As long as we can be quite sure that we cover all cases in which the user cannot recover by automatically logging him/her out, I would suggest to not log the user out in all cases in which he/she can recover him/herself.

**Comment by individual-it** [comment]
fixed by #83
