### ISSUE TITLE
boilerplate is missing / improper.

### ISSUE THREAD

**Issue by purnendudash** [owncloud/moodle-repository_ocis#93]
All plugin file should have some common explicit GPL license statement. Kindly check and include the same.

For more information on this see:
https://moodledev.io/general/community/plugincontribution/checklist#boilerplate

https://github.com/owncloud/moodle-repository_ocis/blob/7631344101dc97554f4f06915fe0933450dacb76/version.php#L2

**Comment by individual-it** [comment]
Sorry I don't understand.
The statement is in lines 4-7: 
https://github.com/owncloud/moodle-repository_ocis/blob/7631344101dc97554f4f06915fe0933450dacb76/version.php#L4-L7

**Comment by purnendudash** [comment]
Kindly check this - https://moodledev.io/general/development/policies/codingstyle#files

**Comment by danmarsden** [comment]
Thanks @individual-it - the fact this has a gpl statement means it's not an approval blocker in the plugins database, but keep in mind Moodle's codechecker tools which check for compliance with the standard guidelines looks for our standard template text - so if you decide to implement #24 - (which I hope you do, because it helps a lot with stuff like this.) you will get a bunch of errors related to this so you might want to consider using the standard templates.

Of course - you don't need to use github ci to check your compliance with the standards - you can install:
https://moodle.org/plugins/local_codechecker
and:
https://moodle.org/plugins/local_moodlecheck

to run some of the tests locally -

**Comment by individual-it** [comment]
- phpcs already runs in CI
- I've ran the local doc checker before submitting the extension to moodle, re-running it now it found some issues in test code (we didn't had that code when releasing the last time) that will be tracked in #97.
- local code checker is also happy 
![grafik](https://github.com/owncloud/moodle-repository_ocis/assets/2425577/f4b08b1b-f373-4c6a-bdc9-968698d7c5ac)

**Comment by danmarsden** [comment]
nice work - keep in mind that the github actions runs a bunch of other checks as well - so just because codechecker and moodelcheck are passing - won't mean that the standard github actions will pass as they run a bunch of other tests as well.

I think here's the part where it triggers the boilerplate test:
https://github.com/moodlehq/moodle-plugin-ci/blob/main/tests/Command/CodeCheckerCommandTest.php#L100

**Comment by danmarsden** [comment]
well - that's not the part that triggers it, but it's where it triggers the report on the failure.

**Comment by individual-it** [comment]
fixed by #102 
The CI now runs moodle github actions
