### ISSUE TITLE
Incorrect camel case in some string.

### ISSUE THREAD

**Issue by purnendudash** [owncloud/moodle-repository_ocis#95]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

https://github.com/owncloud/moodle-repository_ocis/blob/7631344101dc97554f4f06915fe0933450dacb76/lang/en/repository_ocis.php#L46

**Comment by individual-it** [comment]
@phil-davis could you please have a look at https://github.com/owncloud/moodle-repository_ocis/blob/main/lang/en/repository_ocis.php and comment on which of the strings should be capital case and which not.
IMO `Show Project Drives` should be capital because `Project Drives` is a name of a thing in oCIS also `ownCloud Infinite Scale`, because that is the official name of the product (see e.g. https://doc.owncloud.com/ocis/5.0/#introduction)
But I might be wrong, English grammar is not my strong-hold.

**Comment by phil-davis** [comment]
The strings look OK to me.
"ownCloud" is the name of the organisation, which has chosen to have it written like that.
"Infinite Scale" is an official product name, so needs upper-case.

"X... Project Drives", "X... Personal Drive", "X... Shares" are open to interpretation. A "Drive" is a normal word for a "storage device/thing" in computer-land. The types of drives "Project" and "Personal" are not super-special words only for the Infinite Scale product. Similarly, "file shares" is terminology that could be used in lots of file-handling products.

So strings like "Show Personal Drive" can be "Show personal drive" without losing anything much.

**Comment by phil-davis** [comment]
PR #101 has suggested changes for this issue.

**Comment by individual-it** [comment]
@purnendudash please review the strings again after #101
Thank you
